language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g yarn codecov
after_success:
  - yarn run semantic-release
before_script:
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run lint-docs
  - yarn run cover
  - yarn run build
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
