language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '6'
after_success:
  - npm run semantic-release
before_script:
  - yarn add --global codecov
script:
  - yarn run lint
  - yarn run cover
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
