api:
  host: http://localhost
  path: /otp/routers/default
  port: 8001
# Add suggested locations to be shown as options in the form view.
# locations:
#   - id: 'airport'
#     icon: 'plane'
#     name: 'Portland International Airport (PDX)'
#     lat: 45.587579
#     lon: -122.593084
#   - id: 'zoo'
#     icon: building
#     lat: 45.51010444232195
#     lon: -122.71607145667079
#     name: Oregon Zoo, Portland, OR

### The persistence setting is used to enable the storage of places (home, work),
### recent searches/places, user overrides, and favorite stops. Currently the
### only strategy is localStorage (which is used by default). It also must be
### enabled to show the stored locations (see above).
### TODO: add another server-based strategy
persistence:
  enabled: true
  strategy: localStorage

map:
  initLat: 45.52
  initLon: -122.682
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20
    - name: Stamen Toner Lite
      url: http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'

geocoder:
  apiKey: MAPZEN_KEY
  boundary:
    rect:
      minLon: -123.2034
      maxLon: -122.135
      minLat: 45.273
      maxLat: 45.7445
  focusPoint:
    lat: 45.5223452
    lon: -122.6821804
  # required geocoder type. Can be either PELIAS or ARCGIS
  # WARNING: using the ARCGIS geocoder with a persistence strategy of
  #   `localStorage` will result in an error being thrown because ARCGIS
  #   requires the use of a paid account to store geocode results.
  #   See https://developers.arcgis.com/rest/geocode/api-reference/geocoding-free-vs-paid.htm
  type: PELIAS
  # Optional custom api endpoint
  # baseUrl: https://geocoder.example.com/pelias/v1

# Use this mode config for the enhanced Transit+ config
modes:
  transitModes:
    - mode: BUS
      label: Bus
    - mode: TRAM
      label: MAX & Streetcar
    - mode: RAIL
      label: WES
    - mode: GONDOLA
      label: Aerial Tram

  accessModes:
    - mode: BICYCLE
      label: Transit + Bike

  bicycleModes:
    - mode: BICYCLE
      label: Own Bike
      iconWidth: 18


routingTypes:
  - key: ITINERARY
    text: Exact Time

### Use this config for the standard mode selector
# modeGroups:
#   - name: Transit
#     modes:
#       - TRAM
#       - BUS
#   - name: Walk/Bike
#     modes:
#       - WALK
#       - BICYCLE
