name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          prefix: SLUG_

      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Image and Load to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ghcr.io/addismap/AddisMapTransit-web:test-${{ env.SLUG_GITHUB_REF_NAME }}
          load: true
      - name: Tag "latest" and Push to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/addismap/AddisMapTransit-web:test-${{ env.SLUG_GITHUB_REF_NAME }} ghcr.io/addismap/AddisMapTransit-web:latest
          docker push ghcr.io/addismap/AddisMapTransit-web:latest
